name: "Release CI"

on:
  push:
    branches:
      - "master"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: Add plugin for conventional commits
        run: npm install conventional-changelog-conventionalcommits
        working-directory: ./.github/workflows
      - name: Release to GitHub
        working-directory: ./.github/workflows
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: "${{ github.event.pusher.name }}"
          GIT_AUTHOR_EMAIL: "${{ github.event.pusher.email }}"
          GIT_COMMITTER_NAME: "${{ github.event.pusher.name }}"
          GIT_COMMITTER_EMAIL: "${{ github.event.pusher.email }}"
        run: npx semantic-release